version: "3.0"

services:
    lunch-app:
        image: ghcr.io/jamdon2/lunch-app
        restart: always
        depends_on:
            - database
        ports:
            - 80:3000

    database:
        image: mongo:bionic
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db
        env_file:
            - .env.database
