name: Deploy to server
on:
    push:
        branches:
            - main

jobs:
    # build:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v3

    #         - name: Set up QEMU
    #           uses: docker/setup-qemu-action@v2

    #         - name: Set up Docker Buildx
    #           uses: docker/setup-buildx-action@v2

    #         - name: Login to GitHub Container Registry
    #           uses: docker/login-action@v2
    #           with:
    #               registry: ghcr.io
    #               username: ${{ github.repository_owner }}
    #               password: ${{ secrets.GITHUB_TOKEN }}

    #         - run: echo "${{ secrets.env }}" > .env

    #         - name: Build and push
    #           uses: docker/build-push-action@v4
    #           with:
    #               context: .
    #               platforms: linux/amd64,linux/arm64
    #               push: true
    #               tags: ghcr.io/jamdon2/lunch-app:latest

    deploy:
        runs-on: ubuntu-latest
        # needs: build
        steps:
            - name: Tailscale
              uses: tailscale/github-action@v2
              with:
                  authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
            - name: Deploy to server
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      export NVM_DIR=~/.config/nvm
                      source ~/.config/nvm/nvm.sh
                      cd /home/pi/projects/lunch-app
                      git pull
                      npm i
                      npm run build
                      pm2 restart lunchr
                      DISPLAY=:0 xdotool getactivewindow key Control_L+F5
                      exit
